### ISSUE TITLE
Selection serialport undefined

### ISSUE THREAD

**Issue by HeinzRuetschi** [enocean-js/enocean-js#212]
Hello Holger,

There seems to be a new issue with serial port and the enOcean input and output nodes. 
Before the update this was all working fine.

I have reinstalled node-RED and updated your nodes to v.0.8.1 and the node-RED-node-serial port to 0.10.1. However when trying to get the selection in the serial port field of the node, I get now 3 undefined serial port selections and not anymore dev/ttyUSB0 for example. However the hardware is the same

Bus 001 Device 005: ID 152d:0578 JMicron Technology Corp. / JMicron USA Technology Corp. JMS567 SATA 6Gb/s bridge
Bus 001 Device 004: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Bus 001 Device 003: ID 0424:ec00 Microchip Technology, Inc. (formerly SMSC) SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Microchip Technology, Inc. (formerly SMSC) SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

crw-rw---- 1 root dialout 188, 0 Mär 27 10:58 /dev/ttyUSB0

Node-red-log
(node:29117) UnhandledPromiseRejectionWarning: TypeError: "path" is not defined:
at new SerialPort (/home/pi/.node-red/node_modules/node-red-contrib-enocean/node_modules/@serialport/stream/stream.js:115:11)
at openPort (/home/pi/.node-red/node_modules/node-red-contrib-enocean/nodes/enocean-config-node.js:65:15)
at new EnOceanConfigNode (/home/pi/.node-red/node_modules/node-red-contrib-enocean/nodes/enocean-config-node.js:23:7)
at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:164:44)
at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:345:33)
at /usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:212:21
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:29117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
27 Mar 14:58:08 - [warn] [enocean-config-node:d4a2d258.679688] Error: Error: No such file or directory, cannot open undefined

grafik

How can this issue be resolved?

Thank you very much for your support and help.
Greetings Heinz

**Comment by HeinzRuetschi** [comment]
![grafik](https://user-images.githubusercontent.com/8530613/77764009-394e4180-703c-11ea-9c42-69523e282d91.png)

**Comment by HeinzRuetschi** [comment]
Hello Holger,

Update: I've uninstalled the serial port node, stopped and started node-RED again then entered /dev/ttyUSB0 in the serial port field of the enOcean input node. The input node then worked fine, no errors. 
I think it's an issue with the serial port selection in the input node. 
If I select in the serial port field “undefined” as offered, then this will generate errors. As I’ve had mentioned above.
Greetings Heinz

**Comment by HeinzRuetschi** [comment]
Hello Holger, 

thank you very much for you quick reply. 
I have tried and executed your recommendation:

cd  ~/.node-red
rm -rf node_modules/*
npm i

However, this did not resolve the issue; we still have the problem with the serial port interface selection, which remains undefined. 
This happened since we updated node red and your nodes.
Node-RED Version: v1.0.4
Node.js  Version: v12.16.1
node-red-contrib-enocean v0.8.1

We also removed node-RED completely and tried to reinstall node-RED according to the recommendation of nodered.org
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)

However, the issue with the serial port selection remains undefined unless we enter manually /dev/ttyUSB0

Do you have any other recommendation or advice? 
Thanks again for your support and help!

Greetings Heinz

![grafik](https://user-images.githubusercontent.com/8530613/77940826-8ab73480-72b9-11ea-887f-7b1fd378c1c9.png)

**Comment by HeinzRuetschi** [comment]
Hello Holger, 

Update, I've noticed, once I have entered /dev/ttyUSB0 in the serial port selection, it stays in the node-RED config area and therefor also in the input node. 
However, when deleted the port in the node-RED config area, the selection in the EnOcean input node is again undefined. 
So for some unknown reason, the serial port or the port selection in the EnOcean field does not see the /dev/ttyUSB0. It also shows two other undefined ports, as indicated in my previous print screen.

Enclosed please find the log when executing your recommendation. 
Unfortunately, I did not find any chances in the serial port selection.

rm -rf node_modules/*
pi@RueCoPi3B:~/.node-red $ npm i

> @serialport/bindings@8.0.7 install /home/pi/.node-red/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=arm libc= platform=linux)
make: Verzeichnis „/home/pi/.node-red/node_modules/@serialport/bindings/build“ wird betreten
  CXX(target) Release/obj.target/bindings/src/serialport.o
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
  CXX(target) Release/obj.target/bindings/src/poller.o
  CXX(target) Release/obj.target/bindings/src/serialport_linux.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Verzeichnis „/home/pi/.node-red/node_modules/@serialport/bindings/build“ wird verlassen

> @serialport/bindings@2.0.8 install /home/pi/.node-red/node_modules/node-red-contrib-enocean/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=arm libc= platform=linux)
make: Verzeichnis „/home/pi/.node-red/node_modules/node-red-contrib-enocean/node_modules/@serialport/bindings/build“ wird betreten
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:
../src/serialport.cpp:329:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 an::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
                                                                              ^
In file included from /home/pi/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/pi/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:330:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 an::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
                                                                              ^
In file included from /home/pi/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/pi/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp:331:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 an::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
                                                                              ^
In file included from /home/pi/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/pi/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:
../src/serialport.cpp:378:106: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 ::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
                                                                              ^
In file included from /home/pi/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/pi/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../../../../nan/nan.h:54,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/home/pi/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/pi/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
  CXX(target) Release/obj.target/bindings/src/poller.o
  CXX(target) Release/obj.target/bindings/src/serialport_linux.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Verzeichnis „/home/pi/.node-red/node_modules/node-red-contrib-enocean/node_modules/@serialport/bindings/build“ wird verlassen

> serialport@8.0.7 postinstall /home/pi/.node-red/node_modules/serialport
> node thank-you.js

Thank you for using serialport!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/serialport/donate


npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

added 177 packages from 102 contributors and audited 483 packages in 86.626s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Greetings
Heinz

**Comment by HeinzRuetschi** [comment]
Hello Holger,

Just a quick update. 
Today we tested the older node-red-contrib-enocean@0.7.9 version with the 
node-RED Version: v1.0.4 and Node.js  Version: v12.16.1 
We've noticed tha the serialport selection for the /dev/ttyUSB0 option is available again.
So we think the issue with the seriaport option is related to the node-red-contrib-enocean update v0.8.1
![grafik](https://user-images.githubusercontent.com/8530613/78276407-4aeb8980-7513-11ea-8501-e7d40e9c04d7.png)

We hope this is of help to you.
Greetings Heinz

**Comment by HeinzRuetschi** [comment]
With the above configuration, the serialport /dev/ttyUSB0 does not work anymore. 
None of the enOcean products is recognised anymore, even though the USB enOcean Interface LED is blinking when enOcean push buttons are used.
 
So there is definitely a function issue with the port and the node-red-contrib-enocean@0.7.9. in combination with node-RED Version: v1.0.4

When updating to node-red-contrib-enocean@0.8.1 the enOcean products are again recognised. However the serialport selection for /dev/ttyUSB0 is undefined.


![grafik](https://user-images.githubusercontent.com/8530613/78280130-e3383d00-7518-11ea-9731-13b0d50c6ef6.png)

**Comment by Holger-Will** [comment]
should be fixed in v0.8.4

**Comment by HeinzRuetschi** [comment]
Holger, 
Super and thank you very much for all your support and great work!
Greetings Heinz

**Comment by Holger-Will** [comment]
thank you for your patience and all the testing you do!
