### ISSUE TITLE
Nodon roller shutter - D2-05-00 - TypeError: Cannot read property 'datafield' of undefined

### ISSUE THREAD

**Issue by hhenkel** [enocean-js/enocean-js#226]
I'm currently trying to get a [nodon roller shutter module](https://nodon.fr/en/nodon/the-enocean-roller-shutter-module/) to work with nodered, however I seem to either have an error in my payload data or there is something broken with the eep used by the eep-transcoder.js for the device.

I see the following error:
```
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'datafield' of undefined
    at getPayloadLengthFromEEPDescriptor (/data/node_modules/@enocean-js/eep-transcoder/src/eep-transcoder.js:349:18)
    at encodeData (/data/node_modules/@enocean-js/eep-transcoder/src/eep-transcoder.js:369:23)
    at RadioERP1.encode (/data/node_modules/@enocean-js/radio-erp1/src/radio-erp1.js:129:20)
    at EnOceanOutputNode._inputCallback (/data/node_modules/node-red-contrib-enocean/nodes/enocean-out.js:47:13)
    at EnOceanOutputNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:200:18)
    at Immediate.<anonymous> (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
```
When running a inject with the following msg.payload:
```
{
    "data": {
        "POS": 127,
        "ANG": 127,
        "REPO": 0,
        "LOCK": 0,
        "CHN": 15,
        "CMD": 1
    },
    "meta": {
        "eep": "d2-05-00",
        "channel": 15,
        "data": 1
    }
}
```
I tried to debug it remotely as nodered is running on raspberry pi and I believe the 'problem' is caused by this [part of the code](https://github.com/enocean-js/enocean-js/blob/master/packages/node_modules/%40enocean-js/eep-transcoder/src/eep-transcoder.js#L148-L152). As I'm not that familiar with node.js I struggle to fully understand why the "cond" variable is "NaN" in my case.

I have also a [nodon 1 channel relay switch](https://nodon.fr/en/nodon/enocean-relay-switch-1-channel-dry-contact/) working with nodered, therefore I believe it is not a general issue with my installation.

**Comment by remisharrock** [comment]
Can you paste the flow (export as JSON and paste it) I can try to help you

**Comment by yGuy** [comment]
I ran into the same issue and after quite a bit of analysis I came to the same conclusion as you. The problem is that "cond" is "NaN" and indeed just adding a `|| isNaN(cond)` fixes the issue!

Maybe @Holger-Will can comment on my more thorough analysis and understanding of the code:

Here is a test that fails and that should work with the added "isNan" fix:

```
      radio = RadioERP1.from({ payload: [0], id: 'ff00ff00' })
      radio.encode({ POS: 31, ANG: 47, REPO: 0, LOCK: 0, CHN: 0, CMD: 1 }, { eep: 'd2-05-00', channel: 3, data: 1 })
```

Encoding a package uses a slightly weird logic:

We first create a radio package using the `RadioERP1.from` constructor: in it we actually specify a one-byte payload. However during encoding, some of the modules (d2-05-00) as a condition check for a bit that is beyond the first 8 bits. This actually results in a NaN when testing for that bits. 
The code already has some questionable implementation in there, where it does check if the bits are "0" and then instead of comparing against the payload, it compares against some "data" value. This doesn't scale very well, since every comparison is always made against the same "data" value, though. Also, if for example a condition would be the zero value, this would also not work. IMHO the code should work differently: instead of passing in the "data" in order to find the correct case, we should investigate the case further and see if the conditional bits in question will be set through the other values. This is the case for the d2-05 modules:

```
condition: {
      datafield: {
        bitoffs: '28',
        bitsize: '4',
        value: '0x01'
      }
    },
```
and further down:
```
{
      data: 'Command ID',
      shortcut: 'CMD',
      description: 'Command identifier',
      info: {},
      bitoffs: '28',
      bitsize: '4',
      enum: {
        item: {
          value: '1',
          description: 'Goto command'
        }
      }
```
The condition is for the command and the command always sets the value to 1.

So instead of depending on some "data" that gets piped through to the `getEEPDescriptor` descriptor, we should rather build the payload according to the values that we have and then check for the constants in the condition. Something along the lines of this (where in this case there is no other choice), also worked for me:

```
if (isNaN(cond)) {
          // it could be that we don't have the payload initialized, yet - so we need to make up a payload and check against the condition
          //create an empty payload of the right size
          var length = getPayloadLengthFromEEPDescriptor(item)
          var bytes = new Array(length)
          for (var i = 0; i < length; i++){
            bytes[i] = 0
          }
          var ba = ByteArray.from(bytes)
          // and set all the values where there is no choice anyway, because the value is constant!
          item.datafield && item.datafield.forEach(function(field){
            if (field.enum && field.enum.item && typeof field.enum.item.value !== "undefined"){
              //no choice - set the value!
              ba.setValue(parseInt(field.enum.item.value), parseInt(field.bitoffs), parseInt(field.bitsize))
            }
          })
          // then check against the dummy payload, instead
          if (parseInt(item.condition.datafield.value) === ba.getValue(parseInt(item.condition.datafield.bitoffs), parseInt(item.condition.datafield.bitsize))){
            return true;
          }
        }
```
For the node-red module, the bug could also be worked around by modifying enocean-out.js to not initialize the payload with just one byte, but the above isNaN fix also works for me, although I don't really like the fix and would rather see the "data" stuff removed altogether for the encoding phase.

And by the way the same bug also exist in the (very nice!) `eonocean-js eep-info browser` - trying to view the possible commands for d2-05-00 results in exceptions and only some of the cases are shown. 
I came across this issue, first, and there I fixed the problem by prepopulating the payload with the correct values in `eep2JSON`.

I would be happy to create pull-requests. For now I have created a fork and will add the fixes in there so that I can continue my work.

**Comment by Holger-Will** [comment]
there is a lot(!) of room for improvement, I know...
my first intention was to have special nodes or wrappers for more complex eeps but I agree that the transcoder should at least fail gracefully ;-)
i will look into this issue...
