### ISSUE TITLE
[GP-TI]TypeError: Cannot read property 'toString' of undefined(node-red-contrib-enocean@0.8.5)

### ISSUE THREAD

**Issue by mitubato** [enocean-js/enocean-js#228]
When the next frame is received, the EnOcean-in node will stop and will no longer receive data.
Is there any way around it?

---data----
GP_TI （Teach-In): 
rawByte: "a52f05601204ad01604293001641419800132bc053c0534617d813c1459600164143d8001644c053c053c056cf013fa855002c020a"
node-red-node-serialport: Receive Data

---syslog----
Nov 12 05:23:58 armadillo Node-RED[1423]: (node:1441) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.<anonymous> (/root/nodered/node_modules/node-red-contrib-enocean/nodes/enocean-in.js:37:29)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.emit (events.js:315:20)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.EventEmitter.emit (domain.js:486:12)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at addChunk (_stream_readable.js:309:12)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at readableAddChunk (_stream_readable.js:284:9)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.Readable.push (_stream_readable.js:223:10)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.Transform.push (_stream_transform.js:166:32)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser._transform (/root/nodered/node_modules/@enocean-js/serialport-parser/src/serialport-parser.js:91:16)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.Transform._read (_stream_transform.js:205:10)
Nov 12 05:23:58 armadillo Node-RED[1423]:     at ESP3Parser.Transform._write (_stream_transform.js:193:12)
Nov 12 05:23:58 armadillo Node-RED[1423]: (node:1441) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by Holger-Will** [comment]
looking into this...

**Comment by Holger-Will** [comment]
"a52f05601204ad01604293001641419800132bc053c0534617d813c1459600164143d8001644c053c053c056cf013fa855002c020a"
this is not an enocean telegram... testing the parser against this bytestream leads to the parser ignoring it... 

what are you using node-red-node-serialport for? 
the enocean in node comes with its own serialport library. do not share serial ports across multiple config nodes.

**Comment by mitubato** [comment]
Hi,
This data was received using EnOcean Long Range (LPWA).
I have received the data I want correctly.
I'm looking for a way to ignore the data that Node gets stuck in. ..
One serial port is not referenced by multiple Nodes.

**Comment by Holger-Will** [comment]
which device exactly do you use? can link to or post a datasheet

**Comment by mitubato** [comment]
I couldn't find the exact one, but I found the data sheet for the successor EMOT200LH.
https://www.enocean.com/jp/products/dolphin_long_range/emot-200lh/
We are using EMOT100.

It is believed that the data in question is being sent by the teach-in data that is emitted when the sensor is connected with a long-range transmitter called SX-95EV101 / NSOS-100.
I'm sorry, but the datasheet was not found.
