### ISSUE TITLE
UnhandledPromiseRejectionWarning node_modules/@enocean-js/serialport-sender/src/serialport-sender.js:13:18

### ISSUE THREAD

**Issue by cbachmann987** [enocean-js/enocean-js#237]
I am running the node-red-contrib-enocean nodes to control lights. So far everything works fine, but every 2-3 days the system stops reacting on my buttons and starts putting these entries into the system console:

```
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi>
Feb 05 20:31:47 miraculix node-red[528505]:     at processTimers (internal/timers.js:497:7)
Feb 05 20:31:47 miraculix node-red[528505]:     at listOnTimeout (internal/timers.js:554:17)
Feb 05 20:31:47 miraculix node-red[528505]:     at Timeout._onTimeout (/home/christian/.node-red/node_modules/@enocean-js/serialport-sender/src/serialport-sender.js:13:18)
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Error: timeout
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi>
Feb 05 20:31:47 miraculix node-red[528505]:     at processTimers (internal/timers.js:497:7)
Feb 05 20:31:47 miraculix node-red[528505]:     at listOnTimeout (internal/timers.js:554:17)
Feb 05 20:31:47 miraculix node-red[528505]:     at Timeout._onTimeout (/home/christian/.node-red/node_modules/@enocean-js/serialport-sender/src/serialport-sender.js:13:18)
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Error: timeout
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi>
Feb 05 20:31:47 miraculix node-red[528505]:     at processTimers (internal/timers.js:497:7)
Feb 05 20:31:47 miraculix node-red[528505]:     at listOnTimeout (internal/timers.js:554:17)
Feb 05 20:31:47 miraculix node-red[528505]:     at Timeout._onTimeout (/home/christian/.node-red/node_modules/@enocean-js/serialport-sender/src/serialport-sender.js:13:18)
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Error: timeout
Feb 05 20:31:47 miraculix node-red[528505]: (node:528505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi>
Feb 05 20:31:47 miraculix node-red[528505]:     at processTimers (internal/timers.js:497:7)
Feb 05 20:31:47 miraculix node-red[528505]:     at listOnTimeout (internal/timers.js:554:17)
```

I am not sure what causes this - still learning to use node-red. The error source seems to be somewhere within the enocean-js code.

I am using Node-RED v1.2.6, node-red-contrib-enocean 0.8.5 on Fedora 33. Not sure what else to provide to help - as I am having several flows using the enocean nodes and I don't have any idea which one causes the problem, it is difficult to send you flows.

Perhaps this helps to identify versions:

christian on miraculix in @enocean-js/serialport-sender/src via ⬢ v14.15.4 took 8m50s 
❯ npm version
{
  '@enocean-js/serialport-sender': '0.0.16',
  npm: '6.14.10',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.42.0',
  node: '14.15.4',
  openssl: '1.1.1i',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}

Any help where to search will be appreciated - womens acceptance factor of not-working smart light switches is very low ;-)

**Comment by Holger-Will** [comment]
thanks for the report. this is a know issue, and it is already fixed in code. unfortunately, the fix is not published yet, but I hope to get it published today...

> womens acceptance factor of not-working smart light switches is very low ;-)

i know ;-)

**Comment by cbachmann987** [comment]
Ok thanks for the quick answer. So I wait for the next version and test again.

**Comment by Jean-PhilippeD** [comment]
Hello,

I see same logs and it seems to break the connection to my USB device, in which version your fix should be pushed ?

**Comment by cbachmann987** [comment]
Yes, unfortunately it seems you still did not find the time to publish it.. at least not in the node-red-contrib-enocean package.

It seems you have a newer version of the enocean-js, including the enocean-js/serialport-sender from 0.0.16 to 0.1.0.

Unfortunately I did not understand quickly how to integrate that version into my node-red installation.. perhaps somebody can help with that? Eventually the bug itself is fixed (can't say that myself)..

Thanks in advance

**Comment by cbachmann987** [comment]
I manually changed the dependencies to the newer versions here in the repo and installed it locally; this seems to work fine.

- clone the repo somewhere locally 
- change the dependencies to 0.1.0 in https://github.com/enocean-js/enocean-js/blob/master/packages/node-red-contrib-enocean/package.json
- manually install the package with npm install (folder, as described in https://nodered.org/docs/creating-nodes/packaging#testing-a-node-module-locally) and restart node-red

Not sure if this helps somebody, I will continue testing.
